apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  value: "{{ .Values.configmap.data.value }}"
  email: "{{ .Values.configmap.data.email }}"

