apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadminName | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: "{{ .Values.imagePgadmin.repository }}"
          ports:
            - containerPort: {{ (index .Values.services 2).targetPort }}
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: pgadminpwd

