apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
data:
  user: {{ .Values.secret.data.user }}
  db: {{ .Values.secret.data.db }}
  pwd: {{ .Values.secret.data.pwd }}
  pgadminpwd: {{ .Values.secret.data.pgadminpwd }}

