apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: {{ .Values.namespace }}
  labels:
    app: pgadmin
spec:
  type: {{ (index .Values.services 2).type }}
  ports:
    - port: {{ (index .Values.services 2).port }}
      targetPort: {{ (index .Values.services 2).targetPort }}
      nodePort: {{ (index .Values.services 2).nodePort | default 0 }}
  selector:
    app: pgadmin

